package com.eksamen02x003.controllers;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

import hans.westh.projectmanagement.repositories.ProjectRepository;

@Controller
public class ProjectController {
    @Autowired // This gets the bean called ProjectRepository, which is auto-generated by
    // Spring
    private ProjectRepository projectRepo;

    @GetMapping("/project")
    public String project(@RequestParam(name = "id", required = false, defaultValue = "ProjectId") Integer id,
                          Model model) {
        model.addAttribute("id", id);
        return "project.html";
    }

}
